# Generated by Django 4.2.2 on 2023-07-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_coutnry_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coutnry',
            new_name='Country',
        ),
    ]
